from __future__ import annotations
import uuid
from typing import Any, Dict

from app.contracts.intent import IntentEnvelope
from app.contracts.advisory import AdvisoryResponse, ReasonSurface
from app.models.gateway import GATEWAY


def _id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:10]}"


class AdvisoryEngine:
    """
    Advisory = user-facing explanation (Yi 34B on SimRig primary).
    """

    def advise(self, intent: IntentEnvelope, ctx: Dict[str, Any]) -> AdvisoryResponse:
        system = (
            "You are Red Advisory Engine.\n"
            "Explain clearly. Provide a short recommendation, rationale, and what would change your mind."
        )
        user = f"INTENT: {intent.text}\nCONTEXT_KEYS: {sorted(list(ctx.keys()))}"

        res = GATEWAY.chat(
            engine="advisory",
            messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
            options={"temperature": 0.4},
        )

        if res.ok and res.content.strip():
            rec = res.content.strip()[:1200]
            rs = ReasonSurface(
                reason="Advisory generated by model.",
                confidence=0.65,
                what_would_change_my_mind=["Add world model drift signals", "Add execution receipts evidence"],
            )
            dbg = {"model_used": res.used, "fallbacks": res.attempts}
            return AdvisoryResponse(recommendation=rec, reason_surface=rs, debug=dbg)

        # fallback
        rs = ReasonSurface(
            reason="Advisory fallback: model unavailable.",
            confidence=0.3,
            what_would_change_my_mind=["Restore model connectivity (SimRig/Ai-Control)."],
        )
        return AdvisoryResponse(recommendation=f"Received intent: {intent.text}", reason_surface=rs, debug={"error": res.error, "attempts": res.attempts})
